// Renders one of mdview's generated pages, drives it through a list of steps,
// and writes a PNG per step -- the frames of a demo GIF.
//
// Why this exists: `shot` answers "does this look right", and there are things
// about this app that no still can answer. Whether `s` lands where you were
// looking. Whether the outline lights the section you are actually in. Whether
// the theme palette shows you a theme before you commit to it. Those are the
// things a reader of the README wants to see, and prose has been failing to
// show them.
//
// A screen recording would answer them once. It could not be rebuilt when the
// sidebar changes width, it would carry whatever theme and window size the
// recorder happened to have, and it would show the recents and bookmarks of
// whoever pressed record -- which, on a working machine, are client paths. A
// generated reel has none of those problems: `make reels` redraws every demo
// in the docs against the app as it is now, from state that is a literal in a
// spec file rather than anything read off a disk.
//
// It also answers the bridge. The page asks the app for anything it cannot do
// alone -- bookmarking, the diff, committing a theme, saving a comment -- by
// posting to a WKScriptMessageHandler named "mdview", and it checks whether
// one is there before it offers. With no handler registered, `c` says
// "Comments need the app", `g d` does nothing, and `m` is a keypress into the
// void. So this registers that handler under the same name the app uses
// (crates/mdapp/src/window.rs) and answers from the spec's `bridge` table,
// with the same page loads and window.mdview* calls app.rs answers with. It
// does not reimplement the app; it plays back one session of it.
//
// Frames are drawn to an explicit pixel size rather than taken at whatever
// scale comes back. takeSnapshot hands back an NSImage backed by whichever
// screen the offscreen window happened to land on, so the same reel yields
// 900x620 on one run and 1800x1240 on the next -- and a demo that changes
// dimensions when it is rebuilt is not a demo that can be rebuilt. Drawing
// into a bitmap of a known size makes the reel identical on any display, and
// 2x is the size worth keeping: ffmpeg halves it again for the GIF, and text
// downscaled from 2x survives dithering that text rendered at 1x does not.
//
// Nothing here reads the app's preferences. This program links Cocoa and
// WebKit and never touches NSUserDefaults; the pages it loads are generated by
// `mdview --print-html`, which returns before the app ever starts; and every
// recent file, bookmark and comment a reel shows is a literal in its spec. A
// reel cannot leak what it has no way to look up.
//
// Usage:
//   reel <page.html> <steps.json> <out-dir> [width] [height]
//
// The spec is JSON so a step can carry its own dwell time without inventing a
// delimiter, and so the reels diff readably when one is retimed:
//
//   { "width": 900, "height": 620,
//     "pages": { "dark": "target/reels/pages/tour.mocha.html" },
//     "seed": ["window.mdviewSetRecents([{name:'spec.md',dir:'~/demo'}])"],
//     "bridge": { "setTheme:": { "loadByArg": "tour.%s" } },
//     "steps": [
//       { "js": "window.mdviewShowSidebarTab('outline')", "hold": 900 },
//       { "key": "g m", "hold": 700 },
//       { "key": "/" },
//       { "type": "#mdview-find-input", "text": "minimap", "hold": 1200 },
//       { "key": "Escape", "hold": 600 }
//     ] }
//
// A "type" step emits one frame per character, so typing animates rather than
// appearing whole; its `hold` applies to the last character alone. Alongside
// the PNGs the tool writes frames.txt, an ffmpeg concat list carrying those
// durations -- `make reel` feeds it straight to palettegen/paletteuse.
//
// What is still out of reach, and belongs to the running app: live reload on
// save, the native menu bar, the key equivalents, a file dropped on the icon,
// and the window chrome around all of it. docs/tour.md says so in prose rather
// than pretending the reels are the whole app.
//
// Prefer `make reel REEL=reading`, which generates the pages a spec loads and
// assembles the GIF afterwards.

import Cocoa
import WebKit

// Dispatching the events a keyboard would, rather than calling the page's own
// functions: a reel that reached past the key would keep filming after the key
// had broken.
//
// The target matters. The find bar and the comment box own element-level
// keydown listeners, and an event dispatched on `document` never reaches them
// -- there is no capture path down to a descendant -- while the document-level
// handler deliberately steps aside for a focused field. Sending to the focused
// element when there is one, and to `document` otherwise, is what a keyboard
// does and is the only way both sets of listeners see what they expect.
//
// Typing is not a keydown. Nothing in this page reads keystrokes in a field:
// find, the comment box and all three palettes filter on an "input" event and
// read el.value, so a synthetic keydown would leave the field empty.
let prelude = """
window.__reel = {
  keys: function (spec) {
    spec.split(/\\s+/).filter(Boolean).forEach(function (name) { window.__reel.one(name); });
  },

  one: function (name) {
    var init = { bubbles: true, cancelable: true, key: name,
                 shiftKey: false, ctrlKey: false, metaKey: false, altKey: false };
    for (;;) {
      var m = /^(Shift|Ctrl|Meta|Alt)\\+(.+)$/.exec(init.key);
      if (!m) break;
      init[m[1].toLowerCase() + "Key"] = true;
      init.key = m[2];
    }
    // An upper-case letter IS shift, the way a keyboard reports it -- and the
    // key stays cased, because the page reads event.key for N, G and W.
    if (init.key.length === 1 && init.key !== init.key.toLowerCase()) init.shiftKey = true;
    if (init.key === "Space") init.key = " ";
    var el = document.activeElement;
    var target = (el && el !== document.body && el !== document.documentElement) ? el : document;
    target.dispatchEvent(new KeyboardEvent("keydown", init));
    target.dispatchEvent(new KeyboardEvent("keyup", init));
  },

  type: function (selector, text) {
    var el = selector ? document.querySelector(selector) : document.activeElement;
    if (!el) throw new Error("no such field: " + selector);
    if (el !== document.activeElement) el.focus();
    el.value = text;
    el.dispatchEvent(new Event("input", { bubbles: true }));
  }
};
"""

/// Draw the snapshot into a bitmap of exactly this many pixels, so a reel does
/// not change size with the display it was rebuilt on.
func png(_ image: NSImage, pixelsWide: Int, pixelsHigh: Int) -> Data? {
    guard
        let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: pixelsWide, pixelsHigh: pixelsHigh,
            bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
            colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)
    else { return nil }
    rep.size = NSSize(width: pixelsWide, height: pixelsHigh)
    guard let context = NSGraphicsContext(bitmapImageRep: rep) else { return nil }
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = context
    context.imageInterpolation = .high
    image.draw(in: NSRect(x: 0, y: 0, width: pixelsWide, height: pixelsHigh))
    NSGraphicsContext.restoreGraphicsState()
    return rep.representation(using: .png, properties: [:])
}

struct Frame {
    let js: String?    // nil for a navigation step
    let page: String?  // page name to load
    let hold: Double   // seconds this frame dwells in the GIF
    let settle: Double // seconds to wait after acting before snapshotting
}

func fail(_ message: String) -> Never {
    FileHandle.standardError.write((message + "\n").data(using: .utf8)!)
    exit(1)
}

let args = CommandLine.arguments
guard args.count >= 4 else {
    FileHandle.standardError.write(
        "usage: reel <page.html> <steps.json> <out-dir> [width] [height]\n"
            .data(using: .utf8)!)
    exit(2)
}

let src = URL(fileURLWithPath: args[1])
let specURL = URL(fileURLWithPath: args[2])
let outDir = URL(fileURLWithPath: args[3])

guard FileManager.default.fileExists(atPath: src.path) else { fail("no such page: \(src.path)") }
guard let specData = try? Data(contentsOf: specURL) else { fail("cannot read \(specURL.path)") }
guard let spec = (try? JSONSerialization.jsonObject(with: specData)) as? [String: Any] else {
    fail("\(specURL.lastPathComponent) is not a JSON object")
}

// The command line wins over the spec, so one reel can be re-shot at another
// size without editing the file that defines it.
let width = args.count > 4 ? Double(args[4]) ?? 900 : (spec["width"] as? Double ?? 900)
let height = args.count > 5 ? Double(args[5]) ?? 620 : (spec["height"] as? Double ?? 620)

// The page's longest transition is .25s (page.css), so a step that only moves
// the interface is settled well inside .3s. Loads are the exception: KaTeX and
// Mermaid render on load, and a diagram lands half-drawn without a beat.
let defaultSettle = (spec["settle"] as? Double ?? 350) / 1000
let loadSettle = (spec["loadSettle"] as? Double ?? 1400) / 1000
let defaultHold = (spec["hold"] as? Double ?? 800) / 1000
let scale = spec["scale"] as? Double ?? 2
let pages = spec["pages"] as? [String: String] ?? [:]
let seed = spec["seed"] as? [String] ?? []
let bridge = spec["bridge"] as? [String: [String: Any]] ?? [:]

guard let steps = spec["steps"] as? [[String: Any]], !steps.isEmpty else {
    fail("\(specURL.lastPathComponent) has no steps")
}

func js(_ string: String) -> String {
    // JSONSerialization is the one escaper guaranteed to agree with the
    // JavaScript parser about quotes, backslashes and newlines.
    let data = try! JSONSerialization.data(withJSONObject: [string], options: [])
    var text = String(data: data, encoding: .utf8)!
    text.removeFirst()
    text.removeLast()
    return text
}

// Flatten the steps into one frame per snapshot: a `type` step becomes a frame
// per character so the typing animates, and `keys` one per character so the
// jump labels narrow on screen the way they do under a real hand.
var frames: [Frame] = [
    Frame(js: "0", page: nil, hold: (spec["openHold"] as? Double ?? 1200) / 1000, settle: loadSettle)
]
for (index, step) in steps.enumerated() {
    let hold = (step["hold"] as? Double).map { $0 / 1000 } ?? defaultHold
    let settle = (step["settle"] as? Double).map { $0 / 1000 } ?? defaultSettle
    let tick = (step["tick"] as? Double).map { $0 / 1000 } ?? 0.14

    if let page = step["load"] as? String {
        frames.append(Frame(js: nil, page: page, hold: hold, settle: loadSettle))
    } else if let selector = step["type"] as? String {
        guard let text = step["text"] as? String else { fail("step \(index + 1): type without text") }
        for end in 1...max(text.count, 1) {
            frames.append(
                Frame(
                    js: "window.__reel.type(\(js(selector)), \(js(String(text.prefix(end)))))",
                    page: nil, hold: end == text.count ? hold : tick, settle: settle))
        }
    } else if let text = step["keys"] as? String {
        for character in text {
            frames.append(
                Frame(
                    js: "window.__reel.one(\(js(String(character))))", page: nil,
                    hold: character == text.last ? hold : tick, settle: settle))
        }
    } else if let key = step["key"] as? String {
        let times = step["repeat"] as? Int ?? 1
        for _ in 0..<max(times, 1) {
            frames.append(
                Frame(js: "window.__reel.keys(\(js(key)))", page: nil, hold: hold, settle: settle))
        }
    } else if let script = step["js"] as? String {
        frames.append(Frame(js: script, page: nil, hold: hold, settle: settle))
    } else {
        // A bare hold: a frame that changes nothing, for pacing.
        frames.append(Frame(js: "0", page: nil, hold: hold, settle: settle))
    }
}

try? FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)

let app = NSApplication.shared
// .accessory keeps the reel from stealing focus from whatever you are doing.
app.setActivationPolicy(.accessory)

final class Reeler: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
    var frames: [Frame] = []
    var outDir: URL!
    var pixelsWide = 0
    var pixelsHigh = 0
    var index = 0
    var written: [(String, Double)] = []
    var view: WKWebView!
    var navigating = false
    var afterNav: (() -> Void)?

    // ---- The bridge the page expects ------------------------------------

    /// The app answers a posted message by loading a page or by calling back
    /// into the page; so does this, from the spec's table. Longest `prefix:`
    /// match after an exact one, so "setTheme:" catches every theme.
    func userContentController(
        _ controller: WKUserContentController, didReceive message: WKScriptMessage
    ) {
        guard let text = message.body as? String else { return }
        let name = text.contains(":") ? String(text[..<text.firstIndex(of: ":")!]) + ":" : text
        let argument = text.contains(":")
            ? String(text[text.index(after: text.firstIndex(of: ":")!)...]) : ""
        let action = bridge[text] ?? bridge[name] ?? bridge["*"]
        guard let action = action, action["ignore"] as? Bool != true else { return }

        if let format = action["loadByArg"] as? String {
            // The argument can carry more than the name -- setTheme: appends a
            // scroll offset -- so only the first field is the page.
            let head = argument.split(separator: ":").first.map(String.init) ?? argument
            load(page: format.replacingOccurrences(of: "%s", with: head))
        } else if let page = action["load"] as? String {
            load(page: page)
        } else if let script = action["js"] as? String {
            view.evaluateJavaScript(script.replacingOccurrences(of: "%s", with: argument)) { _, _ in }
        }
    }

    func load(page: String) {
        guard let path = pages[page] else { fail("the bridge asked for an unlisted page: \(page)") }
        let url = URL(fileURLWithPath: path)
        guard FileManager.default.fileExists(atPath: url.path) else {
            fail("no such page: \(url.path) (run `make reel-pages`)")
        }
        navigating = true
        view.loadFileURL(url, allowingReadAccessTo: url.deletingLastPathComponent())
    }

    // ---- The step queue --------------------------------------------------

    func webView(_ view: WKWebView, didFinish navigation: WKNavigation!) {
        navigating = false
        // Seeded after every load, because a page that the bridge navigated to
        // is a fresh page: its recents and bookmarks are empty until the host
        // tells it otherwise, which is exactly what the app does.
        let script = seed.isEmpty ? "0" : seed.joined(separator: ";\n")
        view.evaluateJavaScript(script) { _, error in
            if let error = error { fail("seed failed: \(error)") }
            if let resume = self.afterNav {
                self.afterNav = nil
                DispatchQueue.main.asyncAfter(deadline: .now() + loadSettle, execute: resume)
            } else {
                self.run()
            }
        }
    }

    // Recursive rather than a loop: evaluateJavaScript, takeSnapshot and the
    // navigation callback are all asynchronous, and a for-loop over them would
    // fire every step at once and snapshot the last state twenty times.
    func run() {
        guard index < frames.count else { return finish() }
        let frame = frames[index]

        if let page = frame.page {
            afterNav = { [weak self] in self?.snap(frame) }
            load(page: page)
            return
        }

        view.evaluateJavaScript(frame.js ?? "0") { _, error in
            if let error = error {
                fail("step \(self.index) (\(frame.js ?? "")) failed: \(error)")
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + frame.settle) {
                // A key can send the page somewhere -- g d is a whole other
                // page -- and the frame belongs to where it landed, not to the
                // moment it left.
                if self.navigating {
                    self.afterNav = { [weak self] in self?.snap(frame) }
                } else {
                    self.snap(frame)
                }
            }
        }
    }

    func snap(_ frame: Frame) {
        view.takeSnapshot(with: WKSnapshotConfiguration()) { image, error in
            guard let image = image,
                let data = png(image, pixelsWide: self.pixelsWide, pixelsHigh: self.pixelsHigh)
            else {
                fail("snapshot \(self.index) failed: \(String(describing: error))")
            }
            let name = String(format: "%03d.png", self.index)
            do { try data.write(to: self.outDir.appendingPathComponent(name)) } catch {
                fail("could not write \(name): \(error)")
            }
            self.written.append((name, frame.hold))
            self.index += 1
            self.run()
        }
    }

    // ffmpeg's concat demuxer ignores the duration of the final entry, so the
    // last frame is listed twice -- the documented way to make it hold.
    func finish() {
        var list = ""
        for (name, hold) in written {
            list += "file '\(name)'\nduration \(String(format: "%.3f", hold))\n"
        }
        if let last = written.last { list += "file '\(last.0)'\n" }
        do {
            try list.write(
                to: outDir.appendingPathComponent("frames.txt"), atomically: true, encoding: .utf8)
        } catch {
            fail("could not write frames.txt: \(error)")
        }
        print("\(written.count) frames in \(outDir.path)")
        exit(0)
    }

    func webView(_ view: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
        fail("load failed: \(error)")
    }
}

let delegate = Reeler()
delegate.frames = frames
delegate.outDir = outDir
delegate.pixelsWide = Int(width * scale)
delegate.pixelsHigh = Int(height * scale)

let configuration = WKWebViewConfiguration()
// The same name crates/mdapp/src/window.rs registers. The page checks for it
// before offering anything that needs the app, so registering it is the
// difference between filming the app and filming a page refusing to be it.
configuration.userContentController.add(delegate, name: "mdview")
// A user script rather than one evaluateJavaScript: the bridge navigates, and
// a helper installed once would be gone on the page after the first `g d`.
configuration.userContentController.addUserScript(
    WKUserScript(source: prelude, injectionTime: .atDocumentEnd, forMainFrameOnly: true))

let view = WKWebView(frame: NSRect(x: 0, y: 0, width: width, height: height), configuration: configuration)
view.navigationDelegate = delegate
delegate.view = view

// The view must be in a window and on screen, or WebKit never paints and the
// snapshots come back blank.
let window = NSWindow(
    contentRect: NSRect(x: 0, y: 0, width: width, height: height),
    styleMask: [.titled], backing: .buffered, defer: false)
window.contentView = view
window.orderFrontRegardless()

view.loadFileURL(src, allowingReadAccessTo: src.deletingLastPathComponent())

// A reel is longer than a shot, but it must not hang forever either.
DispatchQueue.main.asyncAfter(deadline: .now() + 180) {
    fail("timed out with \(delegate.index) of \(frames.count) frames written")
}

app.run()
